### ISSUE TITLE
Basic Usage of tmap - y contains previously unseen labels

### ISSUE THREAD

**Issue by bscully27** [GPZ-Bioinfo/tmap#4]
In the starter scripts of tmap, I get the error, "y contains previously unseen labels"

show(data=X, graph=graph, color=color, fig_size=(10, 10), node_size=15, mode='spring', strength=0.04)
C:\intelpython3\lib\site-packages\numpy\lib\arraysetops.py:518: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask &= (ar1 != a)
Traceback (most recent call last):
  File "C:\intelpython3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-33-0801f712054c>", line 1, in <module>
    show(data=X, graph=graph, color=color, fig_size=(10, 10), node_size=15, mode='spring', strength=0.04)
  File "C:\intelpython3\lib\site-packages\tmap-1.0-py3.6.egg\tmap\tda\plot.py", line 201, in show
    label_color = legend_lookup.get(color.label_encoder.transform([label])[0], None)
  File "C:\intelpython3\lib\site-packages\sklearn\preprocessing\label.py", line 257, in transform
    _, y = _encode(y, uniques=self.classes_, encode=True)
  File "C:\intelpython3\lib\site-packages\sklearn\preprocessing\label.py", line 110, in _encode
    return _encode_numpy(values, uniques, encode)
  File "C:\intelpython3\lib\site-packages\sklearn\preprocessing\label.py", line 53, in _encode_numpy
    % str(diff))
ValueError: y contains previously unseen labels: [0]

Consolidated script (from https://tmap.readthedocs.io/en/latest/basic.html) is:

from sklearn.cluster.dbscan_ import DBSCAN
from sklearn.preprocessing.data import MinMaxScaler, StandardScaler
from sklearn.preprocessing.data import *

from sklearn import datasets
import pandas as pd
iris = datasets.load_iris()
X = iris.data
X = pd.DataFrame(X,columns = iris.feature_names)

from tmap.tda import mapper, filter
from tmap.tda.cover import Cover

# Step1. initiate a Mapper
tm = mapper.Mapper(verbose=1)

# Step2. Projection
lens = [filter.MDS(components=[0, 1])]
projected_X = tm.filter(X, lens=lens)
clusterer = DBSCAN(eps=0.75, min_samples=1)
cover = Cover(projected_data=MinMaxScaler().fit_transform(projected_X), resolution=20, overlap=0.75)

graph = tm.map(data=StandardScaler().fit_transform(X), cover=cover, clusterer=clusterer)

from tmap.tda.plot import show, Color
y = iris.target
color = Color(target=y, dtype="categorical")
show(data=X, graph=graph, color=color, fig_size=(10, 10), node_size=15, mode='spring', strength=0.04)

**Comment by peakhell** [comment]
this bug has been fixed.
